#TODO this info should move to the database

ROSTERS = {
    "2021": ["Anna",
            "Brad",
            "Brandon",
            "Carol",
            "Greg",
            "Isaac",
            "Jake",
            "Jamila",
            "Katie",
            "Lance",
            "Nate La",
            "Phil",
            "Ruthie",
            "Ryan",
            "Ted",
            "Walt"],
    "2022": ["Brandon",
            "Carol",
            "Chad",
            "Greg",
            "Hunter",
            "Ian",
            "Josh",
            "Lance",
            "Luke",
            "Matthew",
            "Nate Lo",
            "Phil",
            "Ryan",
            "Shane",
            "Ted",
            "Walt",
            "Zach"],
    "2023": ["Brandon",
            "Cam",
            "Carol",
            "Chad",
            "Greg",
            "Hunter",
            "Ian",
            "Josh",
            "Luke",
            "Moises",
            "Nate Lo",
            "Nate Ly",
            "Paul",
            "Phil",
            "Ryan",
            "Ron",
            "Shane",
            "Steve",
            "Ted",
            "Zach"
        ]
}
