ALL_TIME_PLAYERS = [
    "Anna",
    "Brad",
    "Brandon",
    "Cam",
    "Carol",
    "Chad",
    "Greg",
    "Hunter",
    "Ian",
    "Isaac",
    "Jake",
    "Jamila",
    "Josh",
    "Katie",
    "Lance",
    "Luke",
    "Matthew",
    "Moises",
    "Nate La",
    "Nate Lo",
    "Nate Ly",
    "Paul",
    "Phil",
    "Ron",
    "Ruthie",
    "Ryan",
    "Shane",
    "Steve",
    "Ted",
    "Walt",
    "Zach"
]

ROSTERS = {
    "2021": ["Anna",
            "Brad",
            "Brandon",
            "Carol",
            "Greg",
            "Isaac",
            "Jake",
            "Jamila",
            "Katie",
            "Lance",
            "Nate La",
            "Phil",
            "Ruthie",
            "Ryan",
            "Ted",
            "Walt"],
    "2022": ["Brandon",
            "Carol",
            "Chad",
            "Greg",
            "Hunter",
            "Ian",
            "Josh",
            "Lance",
            "Luke",
            "Matthew",
            "Nate Lo",
            "Phil",
            "Ryan",
            "Shane",
            "Ted",
            "Walt",
            "Zach"],
    "2023": ["Brandon",
            "Cam",
            "Carol",
            "Chad",
            "Greg",
            "Hunter",
            "Ian",
            "Josh",
            "Luke",
            "Moises",
            "Nate Lo",
            "Nate Ly",
            "Paul",
            "Phil",
            "Ryan",
            "Ron",
            "Shane",
            "Steve",
            "Ted",
            "Zach"
        ]
}
